-- Primero ejecutar la instrucción de la línea 2 ('CREATE DATABASE')
CREATE DATABASE AseoParaElMundoDB;
-- Ahora, ejecuta todo el resto
USE AseoParaElMundoDB;
CREATE TABLE [dbo].[Productos](
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(50),
    Descripcion NVARCHAR(255),
    Precio DECIMAL(10, 2),
    Stock INT
);

INSERT INTO [dbo].[Productos] (
	Nombre,
	Descripcion,
	Precio,
	Stock
)
VALUES ('Desinfectante_0','Desinfectante_0 proporciona una limpieza profunda y duradera.',11.29,923),
('Limpiador de Cocina_0','Limpiador de Cocina_0 deja impecable y sin manchas.',90.69,791),
('Limpiador Multiusos_0','Limpiador Multiusos_0 ideal para todo tipo de superficies.',57.95,696),
('Jab�n L�quido_0','Jab�n L�quido_0 ideal para todo tipo de superficies.',52.79,129),
('Detergente para Ropa_0','Detergente para Ropa_0 especialmente formulado para la limpieza.',7.73,772),
('Limpiador de Cocina_0','Limpiador de Cocina_0 eficaz en la eliminaci�n de g�rmenes y bacterias.',21.5,636),
('Desinfectante_0','Desinfectante_0 elimina la suciedad',80.5,566),
('Desengrasante_0','Desengrasante_0 proporciona una limpieza profunda y duradera.',43.13,429),
('Jab�n L�quido_0','Jab�n L�quido_0 potente para suciedad dif�cil.',87.09,504),
('Limpiavidrios_0','Limpiavidrios_0 elimina la suciedad',97.33,611),
('Limpiador de Pisos_0','Limpiador de Pisos_0 ideal para todo tipo de superficies.',16.42,592),
('Jab�n L�quido_0','Jab�n L�quido_0 proporciona una limpieza profunda y duradera.',48.57,467),
('Detergente para Ropa_0','Detergente para Ropa_0 deja impecable y sin manchas.',53.69,734),
('Limpiador Multiusos_0','Limpiador Multiusos_0 proporciona una limpieza profunda y duradera.',90.44,175),
('Desengrasante_0','Desengrasante_0 eficaz en la eliminaci�n de g�rmenes y bacterias.',78.71,379),
('Limpiavidrios_0','Limpiavidrios_0 proporciona una limpieza profunda y duradera.',14.39,836),
('Jab�n L�quido_0','Jab�n L�quido_0 proporciona una limpieza profunda y duradera.',43.47,732),
('Limpiador de Pisos_0','Limpiador de Pisos_0 potente para suciedad dif�cil.',45.18,352),
('Limpiador de Muebles_0','Limpiador de Muebles_0 potente para suciedad dif�cil.',27.32,540),
('Jab�n L�quido_0','Jab�n L�quido_0 eficaz en la eliminaci�n de g�rmenes y bacterias.',4.44,183),
('Limpiador de Muebles_0','Limpiador de Muebles_0 perfecto para mantener limpio.',36.74,221),
('Limpiador de Muebles_0','Limpiador de Muebles_0 especialmente formulado para la limpieza.',39.84,211),
('Desinfectante_0','Desinfectante_0 aroma agradable.',39.13,702),
('Limpiador de Muebles_0','Limpiador de Muebles_0 proporciona una limpieza profunda y duradera.',86.87,930),
('Limpiador de Cocina_0','Limpiador de Cocina_0 limpia y protege.',81.13,172),
('Desengrasante_0','Desengrasante_0 potente para suciedad dif�cil.',70.87,531),
('Limpiavidrios_0','Limpiavidrios_0 limpia y protege.',68.07,910),
('Limpiador de Ba�os_0','Limpiador de Ba�os_0 deja impecable y sin manchas.',47.23,639),
('Limpiador de Cocina_0','Limpiador de Cocina_0 elimina la suciedad',99.14,350),
('Limpiador Multiusos_0','Limpiador Multiusos_0 proporciona una limpieza profunda y duradera.',90.42,232),
('Limpiador de Pisos_0','Limpiador de Pisos_0 aroma agradable.',33.08,339),
('Limpiador de Muebles_0','Limpiador de Muebles_0 elimina la suciedad',74.68,801),
('Desengrasante_0','Desengrasante_0 proporciona una limpieza profunda y duradera.',51.92,472),
('Limpiador de Muebles_0','Limpiador de Muebles_0 eficaz en la eliminaci�n de g�rmenes y bacterias.',27.02,687),
('Limpiavidrios_0','Limpiavidrios_0 proporciona una limpieza profunda y duradera.',47.51,585),
('Limpiador de Pisos_0','Limpiador de Pisos_0 elimina la suciedad',10.29,269),
('Limpiador de Muebles_0','Limpiador de Muebles_0 perfecto para mantener limpio.',85.53,449),
('Desinfectante_0','Desinfectante_0 elimina la suciedad',38.74,284),
('Limpiador de Pisos_0','Limpiador de Pisos_0 aroma agradable.',85.03,899),
('Limpiador de Pisos_0','Limpiador de Pisos_0 ideal para todo tipo de superficies.',32.12,180),
('Desinfectante_0','Desinfectante_0 ideal para todo tipo de superficies.',86.17,564),
('Jab�n L�quido_0','Jab�n L�quido_0 aroma agradable.',76.97,308),
('Limpiador de Pisos_0','Limpiador de Pisos_0 proporciona una limpieza profunda y duradera.',35.55,229),
('Detergente para Ropa_0','Detergente para Ropa_0 proporciona una limpieza profunda y duradera.',84.8,994),
('Desinfectante_0','Desinfectante_0 limpia y protege.',17.09,502),
('Limpiador de Cocina_0','Limpiador de Cocina_0 aroma agradable.',19.71,868),
('Desengrasante_0','Desengrasante_0 elimina la suciedad',6.12,458),
('Limpiador de Cocina_0','Limpiador de Cocina_0 proporciona una limpieza profunda y duradera.',83.88,784),
('Desinfectante_0','Desinfectante_0 perfecto para mantener limpio.',21.19,876),
('Limpiador de Ba�os_0','Limpiador de Ba�os_0 potente para suciedad dif�cil.',2.64,119),
('Jab�n L�quido_0','Jab�n L�quido_0 potente para suciedad dif�cil.',92.47,947),
('Limpiador de Ba�os_0','Limpiador de Ba�os_0 perfecto para mantener limpio.',87.75,645),
('Detergente para Ropa_0','Detergente para Ropa_0 especialmente formulado para la limpieza.',88.49,100),
('Limpiador de Cocina_0','Limpiador de Cocina_0 proporciona una limpieza profunda y duradera.',65.89,417),
('Limpiador de Ba�os_0','Limpiador de Ba�os_0 proporciona una limpieza profunda y duradera.',9.17,955),
('Limpiador de Cocina_0','Limpiador de Cocina_0 perfecto para mantener limpio.',83.57,72),
('Limpiavidrios_0','Limpiavidrios_0 perfecto para mantener limpio.',45.22,143),
('Detergente para Ropa_0','Detergente para Ropa_0 limpia y protege.',87.72,819),
('Limpiador de Ba�os_0','Limpiador de Ba�os_0 perfecto para mantener limpio.',23.03,535),
('Desengrasante_0','Desengrasante_0 elimina la suciedad',92.97,570),
('Limpiador de Pisos_0','Limpiador de Pisos_0 proporciona una limpieza profunda y duradera.',87.37,315),
('Desinfectante_0','Desinfectante_0 deja impecable y sin manchas.',35.95,200),
('Limpiador de Cocina_0','Limpiador de Cocina_0 potente para suciedad dif�cil.',80.51,287),
('Desengrasante_0','Desengrasante_0 elimina la suciedad',39.68,305),
('Limpiador de Ba�os_0','Limpiador de Ba�os_0 deja impecable y sin manchas.',65.68,867),
('Detergente para Ropa_0','Detergente para Ropa_0 elimina la suciedad',45.48,901),
('Limpiador de Pisos_0','Limpiador de Pisos_0 potente para suciedad dif�cil.',99.95,931),
('Limpiador de Ba�os_0','Limpiador de Ba�os_0 potente para suciedad dif�cil.',84.99,935),
('Limpiador de Pisos_0','Limpiador de Pisos_0 limpia y protege.',33.03,234),
('Limpiador de Pisos_0','Limpiador de Pisos_0 especialmente formulado para la limpieza.',1.46,183),
('Detergente para Ropa_0','Detergente para Ropa_0 especialmente formulado para la limpieza.',26.4,685),
('Jab�n L�quido_0','Jab�n L�quido_0 aroma agradable.',13.47,493),
('Jab�n L�quido_0','Jab�n L�quido_0 eficaz en la eliminaci�n de g�rmenes y bacterias.',5.12,846),
('Limpiador Multiusos_0','Limpiador Multiusos_0 aroma agradable.',31.27,289),
('Limpiador Multiusos_0','Limpiador Multiusos_0 deja impecable y sin manchas.',4.93,168),
('Limpiavidrios_0','Limpiavidrios_0 potente para suciedad dif�cil.',99.06,558),
('Limpiador de Cocina_0','Limpiador de Cocina_0 elimina la suciedad',30.45,739),
('Limpiador de Muebles_0','Limpiador de Muebles_0 proporciona una limpieza profunda y duradera.',2.48,610),
('Limpiador de Cocina_0','Limpiador de Cocina_0 perfecto para mantener limpio.',92.68,245),
('Desinfectante_0','Desinfectante_0 deja impecable y sin manchas.',56.82,264),
('Limpiavidrios_0','Limpiavidrios_0 ideal para todo tipo de superficies.',18.71,927),
('Limpiavidrios_0','Limpiavidrios_0 deja impecable y sin manchas.',11.92,921),
('Limpiador de Cocina_0','Limpiador de Cocina_0 limpia y protege.',17.02,925),
('Limpiador de Pisos_0','Limpiador de Pisos_0 especialmente formulado para la limpieza.',3.01,808),
('Limpiador de Cocina_0','Limpiador de Cocina_0 deja impecable y sin manchas.',37.46,841),
('Jab�n L�quido_0','Jab�n L�quido_0 ideal para todo tipo de superficies.',19.75,873),
('Desengrasante_0','Desengrasante_0 especialmente formulado para la limpieza.',22.91,835),
('Limpiador de Pisos_0','Limpiador de Pisos_0 eficaz en la eliminaci�n de g�rmenes y bacterias.',97.08,11),
('Limpiador de Pisos_0','Limpiador de Pisos_0 potente para suciedad dif�cil.',89.69,137),
('Limpiavidrios_0','Limpiavidrios_0 perfecto para mantener limpio.',2.46,753),
('Limpiavidrios_0','Limpiavidrios_0 ideal para todo tipo de superficies.',76.49,304),
('Limpiador de Cocina_0','Limpiador de Cocina_0 proporciona una limpieza profunda y duradera.',64.05,445),
('Jab�n L�quido_0','Jab�n L�quido_0 deja impecable y sin manchas.',72.22,479),
('Detergente para Ropa_0','Detergente para Ropa_0 ideal para todo tipo de superficies.',5.17,893),
('Desinfectante_0','Desinfectante_0 potente para suciedad dif�cil.',62.66,591),
('Limpiador de Ba�os_0','Limpiador de Ba�os_0 aroma agradable.',2.77,834),
('Limpiador de Ba�os_0','Limpiador de Ba�os_0 ideal para todo tipo de superficies.',14.93,877),
('Limpiador de Ba�os_0','Limpiador de Ba�os_0 ideal para todo tipo de superficies.',36.99,730),
('Limpiavidrios_0','Limpiavidrios_0 proporciona una limpieza profunda y duradera.',70.31,667),
('Detergente para Ropa_0','Detergente para Ropa_0 ideal para todo tipo de superficies.',49.02,662)